<a href="https://colab.research.google.com/github/bagher2901/colab_deep_learn/blob/main/Perceptron_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import tensorflow.compat.v1 as tf
hello = tf.constant('Hello, Tensorflow!')
sess = tf.Session()
print(sess.run(hello))

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.datasets import load_iris




In [ ]:
iris_data = load_iris()
x = iris_data.data
y = iris_data.target
y = y == 0
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
per = Perceptron()
per.fit(x,y)


Perceptron()

In [ ]:
per.score(x,y)

1.0

In [ ]:
x.shape

(150, 4)

In [ ]:
per.coef_

array([[ 2.2,  4.4, -6.9, -3.5]])

In [ ]:
per.intercept_

array([1.])